package com.example.memorizerbackend.db.admin;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/admin") // This means URL's start with /group (after Application path)
public class AdminController {
    @Autowired // This means to get the bean called AdminRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private AdminRepository adminRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewAdmin (@RequestBody Admin admin) {
        adminRepository.save(admin);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Admin> getAllAdmin() {
        // This returns a JSON or XML with the users
        return adminRepository.findAll();
    }

}