package com.example.memorizerbackend.db.member;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/member") // This means URL's start with /group (after Application path)
public class MemberController {
    @Autowired // This means to get the bean called MemberRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private MemberRepository MemberRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewMember (@RequestBody Member admin) {
        MemberRepository.save(admin);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Member> getAllMembers() {
        // This returns a JSON or XML with the users
        return MemberRepository.findAll();
    }

}