package com.example.memorizerbackend.db.request;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/request") // This means URL's start with /group (after Application path)
public class RequestController {
    @Autowired // This means to get the bean called RequestRepository
                // Which is auto-generated by Spring, we will use it to handle the data
    private RequestRepository requestRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewRequest (@RequestBody Request request) {
        requestRepository.save(request);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Request> getAllRequests() {
        // This returns a JSON or XML with the users
        return requestRepository.findAll();
    }

}